# Generated by Django 3.0.3 on 2020-03-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileTeam',
            fields=[
                ('agileTeamID', models.AutoField(primary_key=True, serialize=False)),
                ('agileTeamName', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(blank=True, max_length=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assoc_id', models.CharField(max_length=10)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('agile_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.AgileTeam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Organization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='agileteam',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Organization'),
        ),
        migrations.AddField(
            model_name='agileteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Team'),
        ),
    ]
